### PR TITLE
Update nix setup

### PR DESCRIPTION
**Pull request by luc-tielen**
This PR continues the work from #22.
I used https://github.com/input-output-hk/haskell.nix/ to keep nix in sync with stack.
I can get it to build on OSX, but I'm still getting an "stdio.h" not found error when compiling the C files. I think I might need to add another nix overlay for this.

You can test it by doing the following:
```bash
$ nix-shell
$ # once inside in the nix-shell you can run your stack commands like you would without nix
```

### CODE REVIEW

**Comment by csabahruska** [comment]
Is this PR ready or is it work in progress?

**Comment by luc-tielen** [comment]
@csabahruska oh that's funny, I was about to ask on gitter channel if this could be merged in. It's ready. 😄

**Comment by luc-tielen** [comment]
Also, it might currently take quite some time to build some dependencies (like GHC), but we could create a cachix instance for grin organization so all build artifacts can be cached (reducing build times of dependencies to simply copying files from remote destination to locally). 
This can be done in a later PR.

**Comment by andorp** [comment]
I have encountered with this while building in debian, the suggested --option seems to be fixing my nex issue. https://github.com/NixOS/nix/issues/3142, building the rest of the universe now...

**Comment by andorp** [comment]
I got this at my debian when stack build/test:

```
<command line>: can't load .so/.DLL for: /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/librt.so (/nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/librt.so: symbol __close_nocancel, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference)
            
--  While building package grin-0.1.0.0 using:
      /home/andorp/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:grin exe:grin test:grin-end-to-end-test test:grin-test --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

It needs further investigation at my machine, but the nix-shell got activated and the stack build started.

**Comment by csabahruska** [comment]
did work on Ubuntu 16.04

**Comment by luc-tielen** [comment]
I tested this on my Macbook with OSX and on my previous Linux laptop with Ubuntu (18.04) and both seemed to compile + run tests, maybe the error is due to the sandboxing option @andorp? Or something different on Debian? 
How do we proceed with this PR? Can it be merged in?

**Comment by andorp** [comment]
@luc-tielen : I think this is not a showstopper as it works 75% of the observed cases. I plan the update my dev machine soon, and hopefully the problem will go away.

**Pull request merged**
